WebApplication3/Models/HangHoa.cs
namespace QuanLy_CircleK.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web.Mvc;

    [Table("HangHoas")]
    public partial class HangHoa

    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [StringLength(50, ErrorMessage = "Mã Hàng Hóa Phải Ngắn hơn 50 ký tự")]
        [DisplayName("Mã Hàng Hóa")]
        public string MaHangHoa { get; set; }

        [DisplayName("Tên")]
        [Required]
        [StringLength(50)]
        public string TenHH { get; set; }

        [DisplayName("Đơn Giá")]
        public decimal DonGia { get; set; }

        [DisplayName("Đơn Vị")]
        [Required]
        [StringLength(50)]
        public string DonViTinh { get; set; }

        public int NhaCCId { get; set; }

        public bool Xoa { get; set; }

        public virtual NhaCC NhaCCs { get; set; }
    }
}

WebApplication3/Controllers/HangHoaController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLy_CircleK.Models;

namespace QuanLy_CircleK.Controllers
{

    public class HangHoaController : Controller
    {
        private NNTDbContext db = new NNTDbContext();

        // GET: HangHoa
        public ActionResult Index()
        {
            var listHangHoa = db.HangHoas.Where(x => !x.NhaCCs.Xoa && !x.Xoa).ToList();
            return View(listHangHoa);
        }

        // GET: HangHoa/Details/5
        public ActionResult Details(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HangHoa hangHoa = db.HangHoas.FirstOrDefault(x => !x.NhaCCs.Xoa && !x.Xoa && x.Id == id);
            if (hangHoa == null)
            {
                return HttpNotFound();
            }
            return View(hangHoa);
        }

        // GET: HangHoa/Create
        [Authorize]
        public ActionResult Create()
        {
            var listNCC = db.NhaCCs.Where(x => !x.Xoa).ToList();
            if(listNCC.Count() == 0)
            {
                return RedirectToAction("Index", "NhaCCs");
            }
            SelectList stlNCC = new SelectList(listNCC, "Ma", "TenNCC");
            ViewBag.Nhacc = stlNCC;
            return View();
        }

        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaHangHoa,TenHH,DonGia,DonViTinh,NhaCCId")] HangHoa hangHoa)
        {
            if (ModelState.IsValid || hangHoa.DonGia <=0)
            {
                if(hangHoa.NhaCCId == 0)
                {
                    return HttpNotFound();
                }
                db.HangHoas.Add(hangHoa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var listNCC = db.NhaCCs.Where(x => !x.Xoa).ToList();
            if (listNCC.Count() == 0)
            {
                return RedirectToAction("Index", "NhaCCs");
            }
            SelectList stlNCC = new SelectList(listNCC, "Ma", "TenNCC");
            ViewBag.Nhacc = stlNCC;

            return View(hangHoa);
        }

        // GET: HangHoa/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HangHoa hangHoa = db.HangHoas.FirstOrDefault(x => !x.NhaCCs.Xoa && !x.Xoa && x.Id == id);
            var listNCC = db.NhaCCs.Where(x => !x.Xoa).ToList();
            SelectList stlNCC = new SelectList(listNCC, "Ma", "TenNCC");
            ViewBag.Nhacc = stlNCC;

            if (hangHoa == null)
            {
                return HttpNotFound();
            }
            return View(hangHoa);
        }

        // POST: HangHoa/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,MaHangHoa,TenHH,DonGia,DonViTinh,NhaCCId")] HangHoa hangHoa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hangHoa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hangHoa);
        }

        // GET: HangHoa/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HangHoa hangHoa = db.HangHoas.FirstOrDefault(x => !x.NhaCCs.Xoa && !x.Xoa && x.Id == id);
            if (hangHoa == null)
            {
                return HttpNotFound();
            }
            return View(hangHoa);
        }

        // POST: HangHoa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HangHoa hangHoa = db.HangHoas.FirstOrDefault(x => !x.NhaCCs.Xoa && !x.Xoa && x.Id == id);
            db.Entry(hangHoa).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [Authorize]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return HttpNotFound();
            }
            string _FileName = "a.xls";
            //duong dan luu file
            string _path = Path.Combine(Server.MapPath("~/Uploads/Excels"), _FileName);
            //luu file len server
            file.SaveAs(_path);
            //đọc dữ liệu từ file excel trả về dạng datatable
            DataTable dt = ReadDataFromExcelFile(_path);
            //ghi dữ liệu từ datatable ở bước trên vào sql
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                HangHoa hh = new HangHoa();
                hh.MaHangHoa = dt.Rows[i][0].ToString();
                hh.TenHH = dt.Rows[i][1].ToString();
                hh.DonGia = Convert.ToDecimal(dt.Rows[i][2].ToString());
                hh.DonViTinh = dt.Rows[i][3].ToString();
                hh.NhaCCId = int.Parse(dt.Rows[i][4].ToString());

                db.HangHoas.Add(hh);
                db.SaveChanges();

            }
            return RedirectToAction("Index");
        }
        public DataTable ReadDataFromExcelFile(string filepath)
        {
            string connectionString = "";
            string fileExtention = filepath.Substring(filepath.Length - 4).ToLower();
            if (fileExtention.IndexOf("xlsx") == 0)
            {
                connectionString = "Provider = Microsoft.ACE.OLEDB.12.0; Data Source =" + filepath + ";Extended Properties=\"Excel 12.0 Xml;HDR=NO\"";
            }
            else if (fileExtention.IndexOf(".xls") == 0)
            {
                connectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + filepath + ";Extended Properties=Excel 8.0";
            }

            // Tạo đối tượng kết nối
            OleDbConnection oledbConn = new OleDbConnection(connectionString);
            DataTable data = null;
            try
            {
                // Mở kết nối
                oledbConn.Open();

                // Tạo đối tượng OleDBCommand và query data từ sheet có tên "Sheet1"
                OleDbCommand cmd = new OleDbCommand("SELECT * FROM [Sheet1$]", oledbConn);

                // Tạo đối tượng OleDbDataAdapter để thực thi việc query lấy dữ liệu từ tập tin excel
                OleDbDataAdapter oleda = new OleDbDataAdapter();

                oleda.SelectCommand = cmd;

                // Tạo đối tượng DataSet để hứng dữ liệu từ tập tin excel
                DataSet ds = new DataSet();

                // Đổ đữ liệu từ tập excel vào DataSet
                oleda.Fill(ds);

                data = ds.Tables[0];
            }
            catch
            {
            }
            finally
            {
                // Đóng chuỗi kết nối
                oledbConn.Close();
            }
            return data;
        }
        //copy large data from datatable to sqlserver
        private void CopyDataByBulk(DataTable dt)
        {
            //lay ket noi voi database luu trong file webconfig
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["DB Context"].ConnectionString);
            SqlBulkCopy bulkcopy = new SqlBulkCopy(con);
            bulkcopy.DestinationTableName = "Ten table";
            bulkcopy.ColumnMappings.Add(0, "ten cot 1");
            bulkcopy.ColumnMappings.Add(1, "ten cot 2");
            bulkcopy.ColumnMappings.Add(2, "ten cot 3");
            con.Open();
            bulkcopy.WriteToServer(dt);
            con.Close();
        }
    }
}

WebApplication3/Views/HangHoa/Create.cshtml
@model QuanLy_CircleK.Models.HangHoa

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h2>Create</h2>
@using (Html.BeginForm("Upload", "HangHoa", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        @Html.TextBox("file", "", new { type = "file" }) <br />
        <input type="submit" value="Upload" />
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Hàng Hóa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.MaHangHoa, htmlAttributes: new { @style = "text-align : left; max-width: 130px;", @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MaHangHoa, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MaHangHoa, "", new { @class = "text-danger" })
                </div>
            </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenHH, htmlAttributes: new { @style = "text-align : left; max-width: 130px;", @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenHH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenHH, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.TenHH, htmlAttributes: new { @style = "text-align : left; max-width: 130px;", @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea id="ckeditor" name="TenHH"></textarea>
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @style = "text-align : left; max-width: 130px;", @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonViTinh, htmlAttributes: new { @style = "text-align : left; max-width: 130px;", @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonViTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonViTinh, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NhaCCs.TenNCC, htmlAttributes: new { @style = "text-align : left; max-width: 130px;", @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.NhaCCId, (IEnumerable<SelectListItem>)ViewBag.Nhacc, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NhaCCId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2" style="text-align: left; max-width: 130px;"></label>
            <div class="col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication3/Views/HangHoa/Delete.cshtml
@model QuanLy_CircleK.Models.HangHoa

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HangHoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenHH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenHH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonViTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonViTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhaCCs.Ma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaCCs.TenNCC)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication3/Views/HangHoa/Details.cshtml
@model QuanLy_CircleK.Models.HangHoa

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>HangHoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt style="text-align : left">
            @Html.DisplayNameFor(model => model.TenHH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenHH)
        </dd>

        <dt style="text-align : left">
            @Html.DisplayNameFor(model => model.DonGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonGia)
        </dd>

        <dt style="text-align : left">
            @Html.DisplayNameFor(model => model.DonViTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonViTinh)
        </dd>

        <dt style="text-align : left">
            @Html.DisplayNameFor(model => model.NhaCCs.TenNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication3/Views/HangHoa/Edit.cshtml
@model QuanLy_CircleK.Models.HangHoa

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>HangHoa</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.MaHangHoa, htmlAttributes: new { @style = "text-align : left; max-width: 130px;", @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaHangHoa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaHangHoa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenHH, htmlAttributes: new { @style = "text-align : left; max-width: 130px;", @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenHH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenHH, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @style = "text-align : left; max-width: 130px;", @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DonViTinh, htmlAttributes: new { @style = "text-align : left; max-width: 130px;", @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DonViTinh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DonViTinh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NhaCCs.TenNCC, htmlAttributes: new { @style = "text-align : left; max-width: 130px;", @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.NhaCCId, (IEnumerable<SelectListItem>)ViewBag.Nhacc, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.NhaCCId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" style="text-align: left; max-width: 130px;"></label>
        <div class="col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication3/Views/HangHoa/index.cshtml
@model IEnumerable<QuanLy_CircleK.Models.HangHoa>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MaHangHoa)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.TenHH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DonGia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DonViTinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NhaCCs.TenNCC)
        </th>
    </tr>

@foreach (var item in Model) {
<tr>
    <th>
        @Html.DisplayFor(modelItem => item.MaHangHoa)
    </th>

    <td>
        @Html.Raw(item.TenHH)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DonGia)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DonViTinh)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.NhaCCs.TenNCC)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
    </td>
</tr>
}

</table>